### ISSUE TITLE
Possible issue with Exporter

### ISSUE THREAD

**Issue by tommyz7** [OpenFinanceIO/smart-securities-standard#19]
Exporter needs to be set up as `addresses[security]` to be able to export funds which means a migrate function needs to be used. `Exporter` itself doesn't have `migrate` functionality so it's a one-way trip.

https://github.com/OpenFinanceIO/smart-securities-standard/blob/4c4ea4cf814a79a380354296173530a94349f003/contracts/Exporter.sol#L32

Also how `Exporter` will get a balance on ERC20 contract?

https://github.com/OpenFinanceIO/smart-securities-standard/blob/4c4ea4cf814a79a380354296173530a94349f003/contracts/Exporter.sol#L33

Perhaps I'm missing something here. I didn't find any `Exporter` tests so I'm not 100% sure how that's working.

**Comment by GambolingPangolin** [comment]
Exporter was experimental and we've decided not to support it for the time being, so I have removed the contract.
