### ISSUE TITLE
Contracts failed deployment on TestRPC

### ISSUE THREAD

**Issue by 1994wyh-WYH** [OpenFinanceIO/smart-securities-standard#7]
I pulled the source code from master branch and tried to deploy the token contracts on TestRPC, but I got error:

  ```
Deploying ARegD506cToken...
  ... 0x......
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
```

I later found that the issue was caused by some "abstract" functions in the contracts to be deployed. Like `totalSupply_ = ICapTables(capTables).totalSupply(index_); ` the .totalSupply() function is not implemented and totalSupply seems to be worthless. I know this is omitted in your dev branch but that branch seems to have similar issue (I haven't done checking that branch yet).

In the master branch, I modified some contracts and it worked. Except for .totalSupply() in CapTables, `startTrading()` in `TheRegS` needs to be implemented since that is declared in `RegS`, the abstract super class of `TheRegS`. I think the problem for other branches can be solved in a similar way.

I deployed it using **Truffle**. The deployment config is:

```
var ARegD506cToken = artifacts.require("./ARegD506cToken.sol");
var CapTables = artifacts.require("./CapTables.sol");
var TheRegD506c = artifacts.require("./TheRegD506c.sol");
var SimpleUserChecker = artifacts.require("./SimpleUserChecker.sol");
var ARegSToken = artifacts.require("./ARegSToken.sol");
var TheRegS = artifacts.require("./TheRegS.sol");
module.exports = function(deployer) {
        deployer.deploy(SimpleUserChecker);
        deployer.deploy(TheRegD506c, 31536000);
        deployer.deploy(CapTables).then(function() {
        return deployer.deploy(ARegD506cToken, 10000000, true, "0x1...", TheRegD506c.address, CapTables.address);}).then(function() {
        return deployer.deploy(TheRegS);}).then(function() {
        return deployer.deploy(ARegSToken, 10000000, "0x...", TheRegS.address, CapTables.address);});
}
```

**Comment by 1994wyh-WYH** [comment]
Sorry it might be a little confusing. The deploy config is for dev-0.2.1 branch. For master branch some arguments are omitted in the constructors of the 2 tokens.

**Comment by GambolingPangolin** [comment]
Hello!  It looks like you are working on an old branch.  **The current development branch is `dev-0.2.x`** and I am going to delete `dev-0.1.2` immediately upon posting this.

We are using a custom deployment method.  *IOU* documentation on how to do the deployment.  For now (assuming `solc` is on your path):
- run `npm run compile` to generate the contract artifacts
- see [here][2] for the deployment logic for the core contracts
- see [here][3] for the issuance logic 
- see [here][1] for an example of using the `S3` sdk to manipulate entities in the system

[1]: https://github.com/OpenFinanceIO/smart-securities-standard/blob/dev-0.2.x/test/issue.spec.ts
[2]: https://github.com/OpenFinanceIO/smart-securities-standard/blob/dev-0.2.x/src/Init.ts
[3]: https://github.com/OpenFinanceIO/smart-securities-standard/blob/dev-0.2.x/src/Issue.ts

It is OK to use truffle to start playing around with the contracts and understanding their interdependencies, but we aim to eventually provide library support for the contract backend and using the library is the recommended path to deployment.
